import type { Metadata } from "next";
import "@/app/styles/globals.css";
import { Provider } from "@/components/ui/provider";
import { Rubik } from "next/font/google";
import { Container } from "@chakra-ui/react";

const rubik = Rubik({
  weight: ["300", "400", "500", "600", "700"],
  style: ["normal", "italic"],
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html className={rubik.className} suppressHydrationWarning lang="en">
      <body>
        <Provider>
          <Container padding="83px">{children}</Container>
        </Provider>
      </body>
    </html>
  );
}